name: Dart and Flutter CI with Caching and Artifacts

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Caching Flutter SDK
      - name: Restore cached Flutter SDK
        id: cache-flutter-restore
        uses: actions/cache@v2
        with:
          path: ~/.flutter
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.yaml') }}

      # Installing system dependencies
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y wget unzip xz-utils

      # Setting up Flutter SDK
      - name: Set up Flutter
        if: steps.cache-flutter-restore.outputs.cache-hit != 'true'
        run: |
          git clone https://github.com/flutter/flutter.git -b stable --depth 1
          export PATH="$PWD/flutter/bin:$PATH"
          flutter doctor

      # Installing Flutter dependencies
      - name: Install Flutter dependencies
        run: flutter/bin/flutter pub get

      # Verifying formatting
      - name: Verify formatting
        continue-on-error: true
        run: flutter/bin/dart format --output=none --set-exit-if-changed .

      # Building APK
      - name: Build APK
        run: ls && flutter/bin/flutter build apk

      # Saving cache
      - name: Save Flutter cache
        id: cache-flutter-save
        uses: actions/cache@v2
        with:
          path: ~/.flutter
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.yaml') }}

      # Downloading artifact
      - name: Download my artifact
        uses: actions/download-artifact@v2
        with:
          name: my-artifact
          path: ./android/build/app/outputs/flutter-apk/app-release.apk

      # Linking artifact to app file
      - name: Link artifact to app file
        run: ls && ln -s ./android/build/app/outputs/flutter-apk/app-release.apk
